# image will be published to ghcr.io/<user>/<name>
name: rockylinux9-atomic
# description will be included in the image's metadata
description: Rocky Linux 9 (atomic)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/hugo-cuenca/rockylinux-base-experimental
image-version: 9-amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - epel-release
      - kernel
      - rpm-ostree
      - bootc
      - fontconfig
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.Loupe
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.font-viewer
        - org.gnome.clocks
        - org.gnome.Papers
        - org.gnome.Contacts
        - org.gnome.Characters
        - app.devsuite.Ptyxis
        - app.drey.Warp
        - com.belmoussaoui.Decoder
        - com.belmoussaoui.Obfuscate
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.mattjakeman.ExtensionManager
        - io.github.giantpinkrobots.flatsweep
        - io.github.ungoogled_software.ungoogled_chromium
        - io.missioncenter.MissionCenter
        - org.libreoffice.LibreOffice
        - org.videolan.VLC
      remove:
        - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

